services:
  # 1. CONTROL PLANE (Node.js)
  control-plane:
    build:
      context: .                      # <--- AQUI É O SEGREDO: Contexto na Raiz
      dockerfile: services/control-plane/Dockerfile
    container_name: goproxy-control-plane
    ports:
      - "4000:4000"
    environment:
      - REDIS_URL=redis://nexus-redis:6379
    depends_on:
      - redis
    networks:
      - nexus-network

  # 2. DATA PLANE (Go)
  data-plane:
    build:
      context: .                      # <--- Contexto na Raiz também para o Go
      dockerfile: services/data-plane/Dockerfile
    container_name: goproxy-data-plane
    ports:
      - "8080:8080"
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - nexus-network

  # 3. REDIS
  redis:
    image: "redis:alpine"
    container_name: nexus-redis
    networks:
      - nexus-network

  # 4. PROMETHEUS
  prometheus:
    image: prom/prometheus:latest
    container_name: nexus-prometheus
    volumes:
      - ./services/data-plane/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - nexus-network

  # 5. GRAFANA
  grafana:
    image: grafana/grafana:latest
    container_name: nexus-grafana
    ports:
      - "3000:3000"
    networks:
      - nexus-network

networks:
  nexus-network:
    driver: bridge